[package]
name = "weishaupt_modbus_scan"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1.47.1", features = ["full"] }
tokio-macros = "2.5.0"
tokio-modbus = { version = "*", default-features = false, features = ["tcp"] }
